# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc9kmfOLYn0HJ3kXOTWEQtfDKJ91BI4n

# Trabalho
"""

#uploaded = files.upload()
[
    {
        "type": "command",
        "details": {
            "key": "python-envs.packages"
        }
    }
]

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import ipywidgets as widgets
from IPython.display import display, HTML

# Download NLTK data
for package in ['stopwords', 'wordnet']:
    try:
        nltk.data.find(f"corpora/{package}")
    except LookupError:
        nltk.download(package)

# Carregar e preparar dados
def prepare_data():
    df = pd.read_csv('steam (1).csv')
    
    # Combinar genres e tags
    df["textual_description"] = (
        df["genres"].fillna("") + " " + df["steamspy_tags"].fillna("")
    ).str.lower()
    
    # Limpar e processar texto
    df["textual_description"] = df["textual_description"].apply(
        lambda x: re.sub(r'[^a-zA-Z\s]', '', x)
    )
    
    stop_words = set(stopwords.words("english"))
    lemmatizer = WordNetLemmatizer()
    
    df["textual_description"] = df["textual_description"].apply(
        lambda x: ' '.join([
            lemmatizer.lemmatize(word) 
            for word in str(x).split() 
            if word not in stop_words
        ])
    )
    
    return df

# Calcular similaridade
def calculate_similarity_matrix(df):
    tfidf_vectorizer = TfidfVectorizer(max_features=5000)
    tfidf_matrix = tfidf_vectorizer.fit_transform(df["textual_description"])
    return cosine_similarity(tfidf_matrix)

def get_similar_games(game_name, df, cosine_sim_matrix, n=10):
    # Busca case-insensitive com correspondência parcial
    matches = df[df['name'].str.lower().str.contains(game_name.lower())]
    
    if matches.empty:
        return []
        
    if len(matches) > 1:
        print(f"Múltiplos jogos encontrados. Usando '{matches.iloc[0]['name']}'")
    
    idx = matches.index[0]
    similarities = pd.Series(cosine_sim_matrix[idx], index=df.index)
    similarities = similarities[similarities.index != idx]
    
    top_matches = similarities.nlargest(n)
    return list(zip(df.loc[top_matches.index, 'name'], top_matches.values))

def create_interface(df, cosine_sim_matrix):
    game_input = widgets.Text(
        value="",
        placeholder="Digite o nome do jogo...",
        description="Nome do Jogo:",
        layout=widgets.Layout(width="50%")
    )
    
    search_button = widgets.Button(
        description="Encontrar Jogos Semelhantes",
        button_style="info",
        icon="search"
    )
    
    output = widgets.Output()
    
    def on_button_click(b):
        with output:
            output.clear_output()
            selected_game = game_input.value
            if not selected_game:
                print("Por favor, digite o nome de um jogo.")
                return
                
            similar_games = get_similar_games(selected_game, df, cosine_sim_matrix)
            
            if not similar_games:
                print(f"Não foi possível encontrar jogos semelhantes para '{selected_game}'.")
                return
                
            results_df = pd.DataFrame(
                similar_games,
                columns=["Nome do Jogo", "Similaridade"]
            )
            results_df.index += 1
            
            display(
                results_df.style.format({"Similaridade": "{:.4f}"})
                .background_gradient(cmap="Blues", subset=["Similaridade"])
            )
    
    search_button.on_click(on_button_click)
    return game_input, search_button, output

def main():
    # Preparar dados
    df = prepare_data()
    cosine_sim_matrix = calculate_similarity_matrix(df)
    
    # Verificar ambiente
    def is_colab():
        try:
            import google.colab
            return True
        except:
            return False
    
    if is_colab():
        # Interface Colab
        game_input, search_button, output = create_interface(df, cosine_sim_matrix)
        display(game_input, search_button, output)
    else:
        # Interface Terminal
        while True:
            print("\nSistema de Recomendação de Jogos")
            print("Digite 'sair' para encerrar")
            game_name = input("\nDigite o nome do jogo: ")
            
            if game_name.lower() == 'sair':
                break
            
            similar_games = get_similar_games(game_name, df, cosine_sim_matrix)
            
            if similar_games:
                results_df = pd.DataFrame(
                    similar_games,
                    columns=["Nome do Jogo", "Similaridade"]
                )
                results_df.index += 1
                print("\n", results_df.to_string())
            else:
                print(f"\nNão foi possível encontrar jogos semelhantes para '{game_name}'.")

if __name__ == "__main__":
    main()